language: php

php:
  - 7.2
  - 7.3

before_install:
  - composer self-update
  - composer validate

install:
  - composer install

script:
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:fixtures:load --env=test --no-interaction
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
