App\Domain\AbsenceCompteur:
  type: entity

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  embedded:
    type:
      class: App\Domain\AbsenceType

  fields:
    joursDisponibles:
      type: integer
    joursTravailles:
      type: integer

  manyToOne:
    personne:
      targetEntity: App\Domain\Personne
      joinColumn:
        name: personne_email
        referencedColumnName: email
